/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FIRSTGUI;
import logic.*;
import java.awt.Color;
import java.io.*;

import javax.swing.JOptionPane;

/**
 *
 * @author Huzaifa
 */
public class AddStudentForm extends javax.swing.JFrame {

    /**
     * Creates new form AddStudentForm
     */
    public AddStudentForm() {
        initComponents();
                setSize(700,600);

               getContentPane().setBackground(Color.DARK_GRAY);

    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        studentlabel = new javax.swing.JLabel();
        addresslabel = new javax.swing.JLabel();
        fathernamelabel = new javax.swing.JLabel();
        idlabel = new javax.swing.JLabel();
        agelabel = new javax.swing.JLabel();
        submitbutton = new javax.swing.JButton();
        backbutton = new javax.swing.JButton();
        idtext = new javax.swing.JTextField();
        addresstext = new javax.swing.JTextField();
        nametext = new javax.swing.JTextField();
        fathernametext = new javax.swing.JTextField();
        agetext = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Student");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        studentlabel.setFont(new java.awt.Font("ZapfEllipt BT", 1, 20)); // NOI18N
        studentlabel.setForeground(new java.awt.Color(255, 255, 255));
        studentlabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        studentlabel.setText("Enter  Student Name ");
        getContentPane().add(studentlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 239, 42));

        addresslabel.setFont(new java.awt.Font("ZapfEllipt BT", 1, 20)); // NOI18N
        addresslabel.setForeground(new java.awt.Color(255, 255, 255));
        addresslabel.setText(" Enter Student Address ");
        getContentPane().add(addresslabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 250, -1, 40));

        fathernamelabel.setFont(new java.awt.Font("ZapfEllipt BT", 1, 20)); // NOI18N
        fathernamelabel.setForeground(new java.awt.Color(255, 255, 255));
        fathernamelabel.setText("Enter Father's name ");
        getContentPane().add(fathernamelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 204, 33));

        idlabel.setFont(new java.awt.Font("ZapfEllipt BT", 1, 20)); // NOI18N
        idlabel.setForeground(new java.awt.Color(255, 255, 255));
        idlabel.setText(" Enter Student ID ");
        getContentPane().add(idlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 217, 39));

        agelabel.setFont(new java.awt.Font("ZapfEllipt BT", 1, 20)); // NOI18N
        agelabel.setForeground(new java.awt.Color(255, 255, 255));
        agelabel.setText(" Enter  Student's Age ");
        getContentPane().add(agelabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 217, 40));

        submitbutton.setText("Submit");
        submitbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(submitbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(612, 520, 80, 30));

        backbutton.setText("Back");
        backbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backbuttonActionPerformed(evt);
            }
        });
        getContentPane().add(backbutton, new org.netbeans.lib.awtextra.AbsoluteConstraints(522, 520, 80, 30));

        idtext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idtextActionPerformed(evt);
            }
        });
        getContentPane().add(idtext, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 310, 227, -1));

        addresstext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addresstextActionPerformed(evt);
            }
        });
        getContentPane().add(addresstext, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 227, -1));

        nametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nametextActionPerformed(evt);
            }
        });
        getContentPane().add(nametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, 227, -1));

        fathernametext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fathernametextActionPerformed(evt);
            }
        });
        getContentPane().add(fathernametext, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 227, -1));

        agetext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agetextActionPerformed(evt);
            }
        });
        getContentPane().add(agetext, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 360, 227, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huzaifa\\OneDrive\\Desktop\\Untitled design.png")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 730, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nametextActionPerformed

    }//GEN-LAST:event_nametextActionPerformed

    private void backbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backbuttonActionPerformed
       // Open the new form
new nEw().setVisible(true);

// Close the current form
this.dispose();

    }//GEN-LAST:event_backbuttonActionPerformed

    private void submitbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitbuttonActionPerformed

    try {
        // 1. Get input values
        String name = nametext.getText().trim();
        String fatherName = fathernametext.getText().trim();
        String address = addresstext.getText().trim();
        String id = idtext.getText().trim();
        String ageText = agetext.getText().trim();

        // 2. Validate inputs
        if (name.isEmpty() || !name.matches("[a-zA-Z ]+")) {
            throw new IllegalArgumentException("Invalid name. Only letters and spaces allowed.");
        }
        if (fatherName.isEmpty() || !fatherName.matches("[a-zA-Z ]+")) {
            throw new IllegalArgumentException("Invalid father's name.");
        }
        if (address.isEmpty() || !address.matches("[a-zA-Z ]+")) {
            throw new IllegalArgumentException("Invalid address.");
        }
        if (id.isEmpty() || !id.matches("\\d+")) {
            throw new IllegalArgumentException("Student ID must be numeric.");
        }
        int age;
        try {
            age = Integer.parseInt(ageText);
            if (age <= 0) throw new IllegalArgumentException("Age must be positive.");
        } catch (NumberFormatException e) {
            throw new IllegalArgumentException("Invalid age. Must be a number.");
        }

        // 3. File existence check
        File file = new File("MUAZ.txt");
        if (!file.exists()) {
            file.createNewFile();
        }

        // 4. Check for duplicate ID
        BufferedReader br = new BufferedReader(new FileReader(file));
        String line;
        boolean duplicate = false;
        while ((line = br.readLine()) != null) {
            if (line.contains("ID: " + id)) {
                duplicate = true;
                break;
            }
        }
        br.close();

        if (duplicate) {
            throw new IllegalArgumentException("Student ID already exists. Enter a unique ID.");
        }

        // 5. Save to file
        BufferedWriter bw = new BufferedWriter(new FileWriter(file, true));
        bw.write("Name: " + name + ", Father: " + fatherName + ", Age: " + age +
                 ", Address: " + address + ", ID: " + id);
        bw.newLine();
        bw.close();

        // 6. Success message
        JOptionPane.showMessageDialog(this, "Student registered successfully!");

        // 7. Clear fields
        nametext.setText("");
        fathernametext.setText("");
        addresstext.setText("");
        idtext.setText("");
        agetext.setText("");

    } catch (IllegalArgumentException | IOException e) {
        JOptionPane.showMessageDialog(this, "Error: " + e.getMessage(), "Input/File Error", JOptionPane.ERROR_MESSAGE);
    }

        
    }//GEN-LAST:event_submitbuttonActionPerformed

    private void fathernametextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fathernametextActionPerformed
        // TODO add your handling code here:
    


        
    }//GEN-LAST:event_fathernametextActionPerformed

    private void addresstextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addresstextActionPerformed
 
        
    }//GEN-LAST:event_addresstextActionPerformed

    private void idtextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idtextActionPerformed
  

        
    }//GEN-LAST:event_idtextActionPerformed

    private void agetextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agetextActionPerformed
   

        
    }//GEN-LAST:event_agetextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddStudentForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddStudentForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addresslabel;
    private javax.swing.JTextField addresstext;
    private javax.swing.JLabel agelabel;
    private javax.swing.JTextField agetext;
    private javax.swing.JButton backbutton;
    private javax.swing.JLabel fathernamelabel;
    private javax.swing.JTextField fathernametext;
    private javax.swing.JLabel idlabel;
    private javax.swing.JTextField idtext;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField nametext;
    private javax.swing.JLabel studentlabel;
    private javax.swing.JButton submitbutton;
    // End of variables declaration//GEN-END:variables
}
