/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FIRSTGUI;
import logic.*;

import java.awt.Color;

/**
 *
 * @author Huzaifa
 */
public class nEw extends javax.swing.JFrame {

    /**
     * Creates new form nEw
     */
    public nEw() {
   
        initComponents();
        setSize(700,600);
                               getContentPane().setBackground(Color.GRAY);



    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        search = new javax.swing.JButton();
        updste = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        rmv_std = new javax.swing.JButton();
        add_std = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        readanddisplay = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        search.setFont(new java.awt.Font("ZapfEllipt BT", 1, 20)); // NOI18N
        search.setText("Search Student");
        search.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchActionPerformed(evt);
            }
        });
        getContentPane().add(search, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 186, 240, 44));

        updste.setFont(new java.awt.Font("ZapfEllipt BT", 1, 20)); // NOI18N
        updste.setText("Update Student");
        updste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updsteActionPerformed(evt);
            }
        });
        getContentPane().add(updste, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 311, 238, 46));

        exit.setFont(new java.awt.Font("ZapfEllipt BT", 1, 20)); // NOI18N
        exit.setText("Exit");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        getContentPane().add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 437, 238, 44));

        rmv_std.setFont(new java.awt.Font("ZapfEllipt BT", 1, 20)); // NOI18N
        rmv_std.setText("Remove Student");
        rmv_std.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rmv_stdActionPerformed(evt);
            }
        });
        getContentPane().add(rmv_std, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 248, 238, 45));

        add_std.setFont(new java.awt.Font("ZapfEllipt BT", 1, 20)); // NOI18N
        add_std.setForeground(new java.awt.Color(51, 0, 51));
        add_std.setText("Add Student");
        add_std.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_stdActionPerformed(evt);
            }
        });
        getContentPane().add(add_std, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 123, 238, 45));

        jLabel1.setFont(new java.awt.Font("ZapfEllipt BT", 1, 40)); // NOI18N
        jLabel1.setForeground(java.awt.Color.lightGray);
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Student Information System");
        jLabel1.setToolTipText("");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 10, 519, 105));

        readanddisplay.setFont(new java.awt.Font("ZapfEllipt BT", 1, 20)); // NOI18N
        readanddisplay.setText("Display ");
        readanddisplay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                readanddisplayActionPerformed(evt);
            }
        });
        getContentPane().add(readanddisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(222, 375, 238, 44));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\Huzaifa\\OneDrive\\Desktop\\Untitled design.png")); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void add_stdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_stdActionPerformed
add_std.setText("Add Student");
add_std.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        new AddStudentForm().setVisible(true);
    }
});

    }//GEN-LAST:event_add_stdActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed

        exit.addActionListener(new java.awt.event.ActionListener() {
                public void actionPerformed(java.awt.event.ActionEvent evt) {
                    System.exit(0);
                }

        });
        

        // TODO add your handling code here:
    }//GEN-LAST:event_exitActionPerformed

    private void readanddisplayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_readanddisplayActionPerformed
        // TODO add your handling code here:
        new readfromfile().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_readanddisplayActionPerformed

    private void searchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchActionPerformed
          search.setText("Search Student");
search.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        new SEARCH().setVisible(true);
    }
});
    }//GEN-LAST:event_searchActionPerformed

    private void rmv_stdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rmv_stdActionPerformed
       rmv_std.setText("Remove Student");
rmv_std.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        new RemoveStudentForm().setVisible(true);
    }
});
    }//GEN-LAST:event_rmv_stdActionPerformed

    private void updsteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updsteActionPerformed
updste.setText("Update Student");
updste.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        new UPDATEE().setVisible(true);
    }
});

    }//GEN-LAST:event_updsteActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(nEw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(nEw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(nEw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(nEw.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new nEw().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_std;
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JButton readanddisplay;
    private javax.swing.JButton rmv_std;
    private javax.swing.JButton search;
    private javax.swing.JButton updste;
    // End of variables declaration//GEN-END:variables
}
